seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/main.rb
    page_type: main
    disabled: false
  - file: ./parsers/sub_category.rb
    page_type: sub_category
    disabled: true
  - file: ./parsers/pagination.rb
    page_type: pagination
    disabled: true
  - file: ./parsers/delivery_tor.rb
    page_type: delivery_tor
    disabled: true
  - file: ./parsers/pickup_tor.rb
    page_type: pickup_tor
    disabled: true
  - file: ./parsers/delivery_van.rb
    page_type: delivery_van
    disabled: true
  - file: ./parsers/pickup_van.rb
    page_type: pickup_van
    disabled: true

exporters:
  - file: ./exporters/items_csv.yaml
    disabled: false